#+BEGIN_COMMENT
.. title: Hitchikers Guide to Ethical Hacking
.. slug: index
.. date: 2017-11-02 10:43:27 UTC
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

#+BEGIN_QUOTE
Not only is it a wholly remarkable book, it is also a highly successful one – more popular than the Celestial Home Care Omnibus, better selling than Fifty-three More Things to do in Zero Gravity, and more controversial than Oolon Colluphid's trilogy of philosophical blockbusters Where God Went Wrong, Some More of God's Greatest Mistakes and Who is this God Person Anyway?

In many of the more relaxed civilizations on the Outer Eastern Rim of the Galaxy, the Hitch-Hiker's Guide has already supplanted the great Encyclopaedia Galactica as the standard repository of all knowledge and wisdom, for though it has many omissions and contains much that is apocryphal, or at least wildly inaccurate, it scores over the older, more pedestrian work in two important respects.

First, it is slightly cheaper; and secondly it has the words DON'T PANIC inscribed in large friendly letters on its cover.” 

*- Douglas Adams, The Hitchhiker's Guide to the Galaxy*
#+END_QUOTE

* About
A Repository for Guides, cheetsheets, and other things generate by staff and students of the CUEH course.

There are two types of content:

** Articles

More structured content, it may be a series of posts dealing with a specific subject.
Or writeup related to course content.  

For the moment Articles will be dealt with by an admin team.  

An Article index can be found [[./articles][here]]


** Posts

Blog like posts on specific topics.  You can get a list of them at [[./posts]]

Posts are intended to be a little more ad-hoc, if appropriate, posts
will be gathered up and turned into an article series.

If you have a sbject you want to let others know about.  Feel free to [[./contribute][contribute]]

* Contributing

There are many subject areas we need to cover, and each person has their own speciality.
Feel free to contribute to the guide:

  - Create your own posts
    - Create a series of posts that can be published as an article
  - Edit other peoples work
    - Fix errors
    - Add more content

Instructions on how to contribute can be found [[./contribute][here]]

